server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 1000
        time-between-eviction-runs: 100000
