server:
  port: 8080
  servlet:
    session:
      timeout: 3600
    application-display-name: jaguar
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    include: core, mybatisplus, redis, shiro