server:
  port: 8088

spring:
  application:
    name: jaguar-system-mgm
  profiles:
    include: mybatisplus, web, swagger, security, redis
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  level:
    org.jaguar: debug
    com.baomidou.mybatisplus.extension.spring: debug
    springfox: error

jaguar:
  modules:
    system:
      mgm:
        verify-code-enable: false
