flowable.cmmn.enabled=false
flowable.form.enabled=false
flowable.idm.enabled=false
flowable.dmn.enabled=false
flowable.content.enabled=false
flowable.content.storage.root-folder=content
flowable.app.enabled=false
flowable.app.deploy-resources=false