flowable:
  cmmn.enabled: false
  form.enabled: false
  idm.enabled: false
  dmn.enabled: false
  content.enabled: false
  content.storage.root-folder: content
  app.enabled: false
  app.deploy-resources: false