spring:
  security:
    user:
      name: codegen
      password: 123456
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          merge-sql: true
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        allow: 127.0.0.1
    dynamic:
      druid:
        initial-size: 1
        max-active: 5
        min-idle: 1
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://jaguar-mysql:3306/jaguar_codegen?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
          username: root
          password: root
          druid:
            db-type: mysql
            filter:
              stat:
                log-slow-sql: true
                merge-sql: true

mybatis-plus:
  type-aliases-package: top.wilsonlv.jaguar.**.model*, com.**.model*
  mapper-locations: classpath*:**/mapper/xml/*.xml
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    local-cache-scope: session
  global-config:
    db-config:
      id-type: id_worker
      update-strategy: NOT_NULL
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted_

jaguar:
  codegen:
    column-type-mapping: {"int":"Integer", "smallint":"Integer", "mediumint":"Integer", "bigint":"Long", "tinyint":"Boolean", "varchar":"String", "text":"String", "longtext":"String", "date":"LocalDate", "datetime":"LocalDateTime", "timestamp":"LocalDateTime"}