spring:
  redis:
    database: 0
    password:
    timeout: 2000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 1000
        time-between-eviction-runs: 100000
    cluster:
      nodes: 127.0.0.1:6379, 127.0.0.1:6380, 127.0.0.1:6381, 127.0.0.1:6382, 127.0.0.1:6383, 127.0.0.1:6384
      max-redirects: 3

