server:
  port: 8090
  servlet:
    session:
      timeout: 3600
      cookie:
        name: JAGUAR-TEST-SESSION-ID
    application-display-name: ${spring.application.name}
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
#    include: security, session-auth, redis
    active: dev
  application:
    name: jaguar-test
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes: #配置路由规则
        - id: jaguar-numbering
          uri: lb://jaguar-numbering
          predicates:
            - Path=/numbering/**
          filters:
            - StripPrefix=1
        - id: system-mgm
          uri: lb://system-mgm
          predicates:
            - Path=/auth/**
            - Path=/system/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:

logging:
  level:
    org.jaguar: debug
    com.baomidou.mybatisplus.extension.spring: debug
    springfox: error
