server:
  port: 8088
  servlet:
    session:
      timeout: 3600
      cookie:
        name: JAGUAR-TEST-SESSION-ID
    application-display-name: jaguar-test
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    include: security, token-auth, redis
    active: dev


logging:
  level:
    org.jaguar: debug
    com.baomidou.mybatisplus.extension.spring: debug
    springfox: error
