server:
  port: 26666

spring:
  application:
    name: jaguar-test
  klock:
    address: localhost:6379
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jaguar_upms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: root
    druid:
      db-type: mysql
      initial-size: 1
      max-active: 5
      min-idle: 1
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          merge-sql: true
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true

mybatis-plus:
  type-aliases-package: top.wilsonlv.jaguar.**.model*, com.**.model*
  mapper-locations: classpath*:**/mapper/xml/*.xml
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    local-cache-scope: session
  global-config:
    db-config:
      id-type: id_worker
      update-strategy: NOT_NULL
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted_

