server:
  port: 8088
  servlet:
    session:
      timeout: 3600
    application-display-name: jaguar-test
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    include: core, mybatisplus, shiro, swagger, code-generator
    active: dev

logging:
  level:
    org.jaguar: debug
    com.baomidou: debug