spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lims?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    password: lxj900221