server:
  port: 8088

spring:
  application:
    name: jaguar-system-mgm
  profiles:
    include: mybatisplus, web, swagger, security, session-auth, redis
    active: dev

logging:
  level:
    org.jaguar: debug
    com.baomidou.mybatisplus.extension.spring: debug
    springfox: error

jaguar:
  modules:
    system:
      mgm:
        verify-code-enable: false
