jaguar:
  shiro:
    authc-enable: true
    redis-session-enable: false
    login-url: /unauthorized
    unauthorized-url: /forbidden
    cookie-name: JAGUAR-JSESSIONID
    filter-chain-definitions: /index.jsp,/*.ico,/unauthorized,/forbidden,/swagger**,/swagger-resources/**,/webjars/**,/*/api-docs,/auth/login,/verify_code/*,/test,/test/**