jaguar:
  modules:
    code-generator:
      default-output-dir: code_genertor/
      default-parent-package: org.jaguar.modules
      default-table-prefix: t_

logging:
  level:
    com.baomidou.mybatisplus.generator: debug
